# Generated by Django 4.2.7 on 2023-11-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='call_sign',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
