# Generated by Django 4.2.7 on 2023-11-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_aircraft_call_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='call_sign',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
